spring.application.name=my-sports-store-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sportsstore}
spring.datasource.username=${DB_USERNAME:sportsstore}
spring.datasource.password=${DB_PASSWORD:sportsstore}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION}

app.cors.allowed-origins=${CORS_URI}
